spring:
  application:
    name: edu-bupt

  redis:
    host: 127.0.0.1
    database: 1


server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging.level.org.springframework.security: DEBUG

