spring:
  application:
    name: service-auth

  redis:
    host: 10.103.241.247
    database: 13


server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://10.103.246.113:8000/eureka/

#logging.level.org.springframework.security: DEBUG

